name: Node Github CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and run tests
      run: |
        cd /home/dipan/actions-runner/_work/chatapp/chatapp/backend
        npm install
      env:
        CI: true

  deploy:
    needs: test
    runs-on: self-hosted

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@v2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pm2 restart server.js
