name: Node Github CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and run tests
      run: |
        cd /home/dipan/actions-runner/_work/chatapp/chatapp/backend
        npm install
      env:
        CI: true

  deploy:
    needs: test
    runs-on: self-hosted

    steps:
    - name: SSH and deploy node app
      run: |
        ssh -o StrictHostKeyChecking=no -p @3002 ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd /var/www/backend && git pull origin dev && npm install && pm2 restart server.js'
